
Honors and Awards {#honors-and-awards .unnumbered}
=================

-   Stadler Mid-Career Excellence in Maize Genetics Award 2016

-   Faculty Development Award in recognition of university service 2015

Teaching and Advising {#teaching-and-advising .unnumbered}
=====================

Instruction {#instruction .unnumbered}
-----------

-   Instructor, Frontiers and Techniques in Plant Science, CSHL, July
    2015

-   Genetics (UC Davis, BIS 101, undergraduate), 2013-2018

-   Ecological Genomics (UC Davis, ECS243, graduate), 2014-2018

-   Faculty advisor, Pioneer Hi-Bred/CAES graduate student symposium in
    plant breeding, 2012-2018

-   Faculty advisor, US-Mexico graduate student exchange program,
    2011-2015

-   Guest lecturer, Plant Biology Core Course, guest lecturer, Fall 2015

#### Advising 

#####  Postdoctoral:

    -   blah

#####     Graduate:

    -   Paul Bilinski (Graduated, currently faculty at )

#####     Dissertation Committees:

    -   blah

#####    Undergraduate:


