### 2017

* Genome Biology  [video abstract](https://www.youtube.com/watch?v=KgIUGHEZ2nM) of  [Wang et al. 2017 paper on maize demography and load](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1346-4). 
*  [Blog post](http://www.pflanzenforschung.de/index.php?cID=12286) (in German) on our [2017 review on domestication](http://www.sciencedirect.com/science/article/pii/S0960982217307856).
* [UCD press release](https://t.co/3MkC6eRDyD) on our transposable element annotation of the new maize genome from [Jiao 2017](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22971.html?foxtrotcallback=true)  
* [NSF research highlight](https://news.science360.gov/obj/story/2caf076f-1759-40c2-9c56-62e3fbbdf44b/tracking-down-jumping-genes-maize) on our transposable element annotation of the new maize genome from [Jiao 2017](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22971.html?foxtrotcallback=true)
* Interview on work-life balance and authorship on the [TapRoot Podcast](https://plantae.org/blog/taproot-podcast-s1e6-population-genetics-authorship-lists-worklife-balance-and-raining-cockroaches-with-jeffrey-ross-ibarra/) 
* [Nature](http://www.nature.com/news/ancient-genomes-show-how-maize-adapted-to-life-at-high-altitudes-1.22403) perspective on [on Swarts et al. 2017](http://www.nature.com/news/ancient-genomes-show-how-maize-adapted-to-life-at-high-altitudes-1.22403)  * [Science Daily](https://www.sciencedaily.com/releases/2017/08/170803141056.htm) perspective on [on Swarts et al. 2017](http://www.nature.com/news/ancient-genomes-show-how-maize-adapted-to-life-at-high-altitudes-1.22403)
* Write-up in [Science](http://science.sciencemag.org/content/357/6348/240) on Jeff's [seminar at SMBE](https://www.slideshare.net/jrossibarra/adaptive-evolution-of-genome-size-across-altitudinal-clines-in-maize) on [Bilinski et al. 2018](http://www.biorxiv.org/content/early/2017/07/13/134528).
* JRI interviewed for [a SciDevNet article on CIMMYT SeeDs](http://www.scidev.net/america-latina/agropecuaria/noticias/maiz-criollo-va-revelando-sus-secretos-de-adaptacion.html).
* Lab [highlighted in AoB Blog](https://aobblog.com/2017/02/hi-im-actuallivingscientist/ as part of the \#ActualLivingScientist movement on social media [blog posts]). 

### 2016

* [Ramos-Madrigal 2016](http://www.cell.com/current-biology/abstract/S0960-9822(16)31120-4) highlighted in [Nature](http://www.nature.com/nature/journal/v539/n7630/full/539471c.html)  
* [Ramos-Madrigal 2016](http://www.cell.com/current-biology/abstract/S0960-9822(16)31120-4) highlighted in [Science](https://t.co/DDOoKctDfR)
* [Ramos-Madrigal 2016](http://www.cell.com/current-biology/abstract/S0960-9822(16)31120-4) highlighted in  [BBC](http://www.bbc.com/news/science-environment-37999506) and * [Ramos-Madrigal 2016](http://www.cell.com/current-biology/abstract/S0960-9822(16)31120-4) highlighted in the [Smithsonian](http://www.smithsonianmag.com/smart-news/lend-me-your-ears-tale-evolution-from-year-old-corn-cob-180961133/)
* JRI quoted in the [Yolo Gardener](http://yolomg.ucanr.edu/newsletters/Yolo_Gardener63920.pdf) for not knowing what he's talking about
* [Video](https://www.youtube.com/watch?v=aXLuWruOmO4) of JRI speaking at JGI
* Paper on [seed filling in domesticated maize](http://www.nature.com/ng/journal/v47/n12/full/ng.3422.html) highlighted by [F1000](http://f1000.com/prime/725901667)

### 2015

* [Fonseca et al 2015](http://www.rilab.org/pdfs/fonseca2015.pdf) highlighted in [UC Davis Press Release](http://news.ucdavis.edu/search/news_detail.lasso?id=11124)
* [Fonseca et al 2015](http://www.rilab.org/pdfs/fonseca2015.pdf) highlighted in multiple blogs, including [Science World Report](http://www.scienceworldreport.com/articles/21122/20150112/origins-maize-dna-tests-reveal-two-paths.htm),  [Archaeology](http://www.archaeology.org/news/2879-150108-southwest-corn-dna), [SiNC](http://www.agenciasinc.es/Noticias/El-maiz-entro-en-el-suroeste-de-EE-UU-hace-4.000-anos-a-traves-de-la-montana), and [The Scientist](http://www.the-scientist.com/?articles.view/articleNo/41865/title/Corn-Chronicle/)
* [Fonseca et al 2015](http://www.rilab.org/pdfs/fonseca2015.pdf) highlighted in [Science magazine](http://news.sciencemag.org/archaeology/2015/01/how-corn-became-corn)
* [Fonseca et al 2015](http://www.rilab.org/pdfs/fonseca2015.pdf) highlighted in [Nature Plants commentary](http://www.nature.com/articles/nplants20149), and   * [Fonseca et al 2015](http://www.rilab.org/pdfs/fonseca2015.pdf) highlighted in [F1000](https://vpn.lib.ucdavis.edu/prime/,DanaInfo=f1000.com+725299665)  
* Our work on highland maize adaptation is briefly mentioned in the [Daily Democrat](http://www.dailydemocrat.com/general-news/20150110/uc-davis-scientists-work-to-id-food-crops-that-can-survive-global-warming).  
* [Interviews with lab members authors](http://morrell-lab.cfans.umn.edu/interviews/interviews.htm) about our 2011 and 2012 papers on domestication for a UMN course on Crop Evolution.
* [Phys.org](http://phys.org/news/2015-11-higher-yielding-crops-sugar-import.html) runs press release on [Sosso et al. 2015](http://www.nature.com/ng/journal/vaop/ncurrent/full/ng.3422.html).
* [Scientific Collections International](http://blog.scicoll.org/2015/11/teosinte-today-maize-tomorrow.html) write-up on our work with Dolores Piperno and gene expression in teosinte grown in ancient climes.
* [Gerke 2013](http://www.genetics.org/content/201/3/1201)  [highlighted by editors](http://www.genetics.org/content/201/3/NP?etoc) in Genetics 



  
