## Service 

Click on a triangle for a brief summary of individual items requiring substantial effort.  

#### Department
- <details>
    <summary>Section Chair for Agricultural Plant Biology, 2015-2018
</summary>
    <p style="margin-left: 30px">This appointment requires ~10% of my time each year (estimated 250 hrs), consisting of writing merit/promotion letters for one section of the department and serving as acting chair. 
</p></details> 
- <details>
    <summary>Executive committee, 2015-2018
</summary>
    <p style="margin-left: 30px">Attended monthly meetings of the executive committee, participated in email discussion on various departmental issues. 
</p></details> 
- Academic planning committee, 2015-2016, 2018
- <details>
    <summary> Search committee on Climate Adaptation, 2017
</summary>
    <p style="margin-left: 30px">Attended multiple committee meetings and interviews and recruited candidates.
</p></details> 
-   Hatch/AES review, Plant Sciences 2018
-   Junior faculty mentor committee, Plant Sciences, 2017
- GSR Awards Committee, 2017

#### College 
-   College review, NSF limited submission, 2018
- <details>
    <summary>Chair, Search Committee for Dept. Chair of Plant Sciences, 2016
</summary>
    <p style="margin-left: 30px">Lead the search committee for the new department chair. Significant time commitments in recruiting candidates, writing the search plan, administrating the search, interviewing candidates, and coordinating with the Dean's Office.
</p></details> 

#### University 
-   Campus Disciplinary Peer Review committee on sexual violence and harassment, 2017-2018
-   Campus Task Force on Bioinformatics, 2017-2018
-   Campus High Performance Computing Advisory Committee, 2016-2018
-   Genome Center Bioinformatics Core Advisory Board, 2016
-   UC Davis representative, UC-Mexico Initiative committee on the
    environment, 2014-2016
-   Admissions committees: Population Biology, 2015; Ecology, 2015

#### Professional 

-   Maize Genetics Steering Committee, 2018
-   Maize Genetics Awards Committee, 2017
-   [Advisory Board, PeerJ Preprints,
    2016-2018](https://peerj.com/rossibarra/)
  - <details>
    <summary>External search committee, Dept. Plant Biology, Swedish University
    of Agricultural Sciences (2016)
</summary>
    <p style="margin-left: 30px">Reviewed dossiers, interviewed candidates, met with search committee to recommend hiring.
</p></details> 
-   Editorial Boards (manuscripts handled during review period in
    parentheses):
    - <details>
    <summary>[Senior Editor, Genes, Genomes, and Genetics, 2017-2018
        (110)](http://www.g3journal.org/content/editorial-board-0)
</summary>
    <p style="margin-left: 30px">Involves weekly meetings with editorial staff and mutliple hours a week overseeing manuscript reivew and decisions.  </p></details> 
    -   [Associate Editor, Genes, Genomes, and Genetics, 2014-2018
        (36)](http://www.g3journal.org/content/editorial-board-0)
    -   [Senior Editor, PeerJ, 2018
        (49)](https://peerj.com/sections/plant-biology/)
    -   [Academic Editor, PeerJ, 2013-2018
        (11)](https://peerj.com/rossibarra/)
    -   Associate Editor, Genetics, 2018 (1)
    -   [Associate Editor, PLoS Genetics, 2018
        (2)](http://journals.plos.org/plosgenetics/s/editorial-board)
    -   Guest Editor, PLoS Genetics, 2016-2017 (2)
    -   Editor, Axios Reviews (now defunct), 2013-2017 (2)
    -   Guest Editor, PNAS, 2018 (1)
    -   Guest Editor, eLife, 2016 (1)

-   Journal peer review: 33 papers during review period, including for
    Nature, Cell, Nature Genetics, Nature Communications, Nature Plants,
    PNAS, Plant Cell, eLife, Genome Research, Trends in Plant Science,
    and Current Biology
- Grant review: NSF, 2016-2017 (2); Swiss NSF 2016; GWIS 2016; Israeli SF 2016  
- External promotion review letter writer for 3 universities, 2016
#### Public Outreach 

-   Skype A Scientist: 6 presentations to public K-12 classrooms in the
    US (4 states) and Spain (in Spanish), 2017-2018
-   [TapRoot podcast episode on authorship and work/life
    balance](https://plantae.org/taproot-podcast-s1e6-population-genetics-authorship-lists-worklife-balance-and-raining-cockroaches-with-jeffrey-ross-ibarra/),
    Aug 2017
-   [Davis Science
    Cafe](https://capscicomm.org/tag/jeffrey-ross-ibarra/), Aug 2016
-   UC Master Gardeners, May 2016
